### ISSUE TITLE
docker安装后，找不到管理员的账号密码信息

### ISSUE THREAD

**Issue by modcscom** [imcloudfloating/Cloud-OJ#36]
默认的账号信息在哪里呢？

**Comment by imcloudfloating** [comment]
Wiki里面的那个版本已经很久没有维护了，默认的用户和密码应该都是root

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月28日 11:15
收件人: ***@***.***>
抄送: ***@***.***>
主题: [imcloudfloating/Cloud-OJ] docker安装后，找不到管理员的账号密码信息 (Issue #36)


默认的账号信息在哪里呢？

―
